//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogProject.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostLike
    {
        public int PLid { get; set; }
        public int Pid { get; set; }
        public int Uid { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual User User { get; set; }
        public virtual Post Post { get; set; }
    }
}
