//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MidProject.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipe()
        {
            this.RecipeRatings = new HashSet<RecipeRating>();
        }
    
        public int Rid { get; set; }
        public string RecipeTitle { get; set; }
        public string RecipeIngridient { get; set; }
        public string RecipeInstructions { get; set; }
        public System.DateTime RecipePostTime { get; set; }
        public int Uid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipeRating> RecipeRatings { get; set; }
        public virtual User User { get; set; }
    }
}
