//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MidProject.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeRating
    {
        public int RTid { get; set; }
        public int Uid { get; set; }
        public int Rid { get; set; }
        public string RecipeRating1 { get; set; }
    
        public virtual Recipe Recipe { get; set; }
        public virtual User User { get; set; }
    }
}
